sudo: false
language: scala
scala:
  - 2.11.8

script:
  - sbt assembly

services:
  - docker

after_success:
  - docker build --build-arg CMD_CONF_DEST_PATH=/root/stuff-doer/config/application.conf -t egorebasko/stuff-doer .

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
