addSbtPlugin("com.timushev.sbt"  %%  "sbt-updates"           % "0.3.4")
addSbtPlugin("com.github.gseitz" %%  "sbt-release"           % "1.0.9")
addSbtPlugin("com.eed3si9n"      %%  "sbt-assembly"          % "0.14.7")
addSbtPlugin("org.scoverage"     %%  "sbt-scoverage"         % "1.5.1")
addSbtPlugin("org.scalastyle"    %%  "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("net.virtual-void"  %%  "sbt-dependency-graph"  % "0.9.1")